import type { MediaItem } from "@/domain/media";

export const featuredMedia: MediaItem = {
  id: "after-the-last-light",
  title: "After the Last Light",
  kind: "Film",
  year: 2025,
  runtime: "2h 08m",
  rating: "8.7",
  description:
    "On the edge of a changing world, a cartographer returns home to map the one place she never understood.",
  genres: ["Adventure", "Drama", "Mystery"],
  badge: "Scout's pick",
  posterGradient: "linear-gradient(145deg, #6d698e 0%, #d87f61 52%, #1b2038 100%)",
};

export const demoMedia: MediaItem[] = [
  {
    id: "glass-harbor",
    title: "Glass Harbor",
    kind: "Film",
    year: 2024,
    runtime: "1h 54m",
    rating: "8.4",
    description: "A storm-chaser finds a quiet town where the weather remembers everything.",
    genres: ["Mystery", "Drama"],
    badge: "Hidden gem",
    posterGradient: "linear-gradient(145deg, #78b9ba 0%, #315f72 48%, #182838 100%)",
  },
  {
    id: "the-orbit-between-us",
    title: "The Orbit Between Us",
    kind: "Series",
    year: 2025,
    runtime: "8 episodes",
    rating: "9.1",
    description: "Two engineers, one impossible mission, and a signal from the dark.",
    genres: ["Sci-Fi", "Adventure"],
    badge: "New season",
    posterGradient: "linear-gradient(145deg, #7771cc 0%, #302e68 48%, #121629 100%)",
  },
  {
    id: "small-hours",
    title: "Small Hours",
    kind: "Film",
    year: 2023,
    runtime: "1h 42m",
    rating: "8.2",
    description: "A late-night radio host helps strangers find their way back to each other.",
    genres: ["Romance", "Drama"],
    posterGradient: "linear-gradient(145deg, #dd9c78 0%, #9d5b68 48%, #3b3047 100%)",
  },
  {
    id: "wild-blue",
    title: "Wild Blue",
    kind: "Series",
    year: 2024,
    runtime: "10 episodes",
    rating: "8.8",
    description: "A rookie crew discovers the ocean is stranger than the stars.",
    genres: ["Adventure", "Sci-Fi"],
    badge: "Fan favorite",
    posterGradient: "linear-gradient(145deg, #61a9a8 0%, #285f75 48%, #192d50 100%)",
  },
  {
    id: "paper-moons",
    title: "Paper Moons",
    kind: "Film",
    year: 2022,
    runtime: "1h 48m",
    rating: "7.9",
    description: "A brother and sister turn their grandmother's stories into a map of the city.",
    genres: ["Family", "Drama"],
    posterGradient: "linear-gradient(145deg, #efc27d 0%, #d77b61 48%, #62435e 100%)",
  },
  {
    id: "north-of-nowhere",
    title: "North of Nowhere",
    kind: "Series",
    year: 2025,
    runtime: "6 episodes",
    rating: "8.6",
    description: "A small-town archivist unearths a mystery hidden in the snow.",
    genres: ["Mystery", "Thriller"],
    badge: "Just added",
    posterGradient: "linear-gradient(145deg, #9ab9c8 0%, #536f88 48%, #222e45 100%)",
  },
  {
    id: "velvet-static",
    title: "Velvet Static",
    kind: "Film",
    year: 2024,
    runtime: "2h 01m",
    rating: "8.1",
    description: "In a city tuned to one frequency, an underground DJ changes the station.",
    genres: ["Thriller", "Sci-Fi"],
    posterGradient: "linear-gradient(145deg, #e47e98 0%, #87427c 48%, #241e45 100%)",
  },
  {
    id: "good-company",
    title: "Good Company",
    kind: "Series",
    year: 2023,
    runtime: "12 episodes",
    rating: "8.3",
    description: "A mismatched neighborhood crew learns that showing up is its own adventure.",
    genres: ["Comedy", "Family"],
    posterGradient: "linear-gradient(145deg, #b5d27c 0%, #62977a 48%, #2d5361 100%)",
  },
];
